set style line 1 lt rgb "#B0171F"
set style line 2 lt rgb "blue"
set style line 3 lt rgb "magenta"
set style line 4 lt rgb "spring-green"
set style line 5 lt rgb "dark-turquoise"
set style line 6 lt rgb "coral"
set style line 7 lt rgb "salmon"
set style line 8 lt rgb "navy"
set style line 9 lt rgb "purple"
set style line 10 lt rgb "#DA70D6"
set style line 11 lt rgb "gray"
set style line 12 lt rgb "dark-gray"
set style line 13 lt rgb "black"
set style increment user
